version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://admin:F0rtAir325$@confortaire-db.ch02mm6o0f15.ap-south-1.rds.amazonaws.com:3306/confortaire
      - SECRET_KEY=87d11ee34dd1befca81f051b2fe16d06b7420bdd8e31a0d4a11979e2abdc2357
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"              # Map port 80 inside the container to 80 outside
    container_name: confortaire-frontend
    restart: unless-stopped
